2nd module
js-tasks-ru/jsbasic-20210325_klimhammet62 pull request #11
Opened 2021-04-07 20:16 UTC by klimhammet62

5 exercises

2021-04-07 20:16 UTC, jsru commented
Добавляю преподавателя (@koalex) для код-ревью.

2021-04-08 06:58 UTC, koalex requested changes
исправь замечание `1-module/5-task`

2021-04-08 06:58 UTC, koalex commented on 1-module/5-task/index.js
> +    return str.slice(0,19) + '…';
тут ты подглядел в тесты и написал 19. А если будет не 19? Надо `maxlength - 1`

2021-04-08 19:01 UTC, klimhammet62 commented on 1-module/5-task/index.js
> +    return str.slice(0,19) + '…';
> тут ты подглядел в тесты и написал 19. А если будет не 19? Надо `maxlength - 1`

обновил.

2021-04-09 10:37 UTC, klimhammet62 reviewed
i change this task

2021-04-11 15:55 UTC, koalex approved these changes

2021-04-11 15:55 UTC, koalex approved these changes

2021-04-11 15:55 UTC, merged